spring:
  application:
    name: review-service
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    hostname: ${DOMAIN_NAME}
    non-secure-port-enabled: true
    non-secure-port: 80
    health-check-url: ${eureka.instance.hostname}${eureka.instance.healthCheckUrlPath}
    status-page-url: ${eureka.instance.hostname}${eureka.instance.statusPageUrlPath}